### ISSUE TITLE
What is componentDidConnect used for?

### ISSUE THREAD

**Issue by lsanwick** [altjs/connect-to-stores#6]
I've been trying to solve a timing problem with loading indicators (https://github.com/goatslacker/alt/issues/594) and placing my alt action call inside of `componentDidConnect` seems to fix the issue, but I'm not really sure what the purpose of the method is, based on the code in this repo.

Can you enlighten me?

**Comment by goatslacker** [comment]
componentDidConnect gets called after a component is mounted and the stores have been connected. You can put any actions in there and be confident that they will be picked up by the component.
